name: eclint check
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: snow-actions/eclint@master
      with:
        command: 'check'
        files: '*.js'
