name: "ECLint-action"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, macos-latest, windows-latest]
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm test
    - uses: ./
      with:
        args: 'check *.js'
